import * as fs from "node:fs/promises";
import * as path from "node:path";

export interface ExportResult {
  exportDir: string;
  files: string[];
  totalFiles: number;
}

export class CodebaseExporter {
  private baseExportDir: string;

  constructor(baseExportDir?: string) {
    this.baseExportDir =
      baseExportDir ??
      process.env.FORGEOS_EXPORT_DIR ??
      path.resolve(process.cwd(), "..", "forgeos-exports");
  }

  public async exportProject(project: { id: string; name: string; requirement: string }, artifacts: any[]): Promise<ExportResult> {
    const slug = (project.name || `project-${project.id.slice(0, 8)}`)
      .toLowerCase()
      .replace(/[^a-z0-9_-]/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");

    const targetDir = path.join(this.baseExportDir, slug);
    await fs.mkdir(targetDir, { recursive: true });

    const createdFiles: string[] = [];

    const writeFile = async (relPath: string, content: string) => {
      const fullPath = path.join(targetDir, relPath);
      await fs.mkdir(path.dirname(fullPath), { recursive: true });
      await fs.writeFile(fullPath, content.trim() + "\n", "utf-8");
      createdFiles.push(relPath);
    };

    // Extract artifact types
    const findArtifact = (type: string) => artifacts.find((a) => a.type === type)?.content;

    const pmContent = findArtifact("ProductSpecification");
    const archContent = findArtifact("ArchitectureSpecification");
    const dbContent = findArtifact("DatabaseSchema");
    const backendContent = findArtifact("BackendImplementation") ?? findArtifact("SourceCode");
    const uiContent = findArtifact("UISpecification");

    // 1. Root README.md
    const readme = `# ${project.name}

> Generated by ForgeOS Multi-Agent Autonomous Software Factory
> Requirement: "${project.requirement}"

## System Overview
- **Architecture**: ${archContent?.architecture?.pattern ?? "Event-Driven Microservices / Modular Monolith"}
- **Database**: PostgreSQL with Prisma ORM
- **Backend**: Fastify TypeScript REST API
- **Frontend**: Next.js React with Tailwind Design System

## Getting Started

\`\`\`bash
# 1. Install dependencies
npm install

# 2. Setup Database Schema
npx prisma generate
npx prisma db push

# 3. Start Backend Server
npm run dev
\`\`\`

## Architecture & Deliverables
Detailed documentation can be found in the \`docs/\` directory:
- \`docs/PRD.md\`: Product Requirements Document & Acceptance Criteria
- \`docs/ARCHITECTURE.md\`: Architecture Decision Records (ADRs) & API Contracts
`;
    await writeFile("README.md", readme);

    // 2. package.json
    const packageJson = {
      name: slug,
      version: "1.0.0",
      description: project.requirement,
      main: "dist/server.js",
      type: "module",
      scripts: {
        dev: "tsx watch src/server.ts",
        build: "tsc",
        start: "node dist/server.js",
        test: "vitest run",
      },
      dependencies: {
        fastify: "^4.26.2",
        "@fastify/cors": "^9.0.1",
        "@prisma/client": "^5.10.2",
        zod: "^3.22.4",
      },
      devDependencies: {
        prisma: "^5.10.2",
        typescript: "^5.4.2",
        tsx: "^4.7.1",
        vitest: "^1.3.1",
        "@types/node": "^20.11.24",
      },
    };
    await writeFile("package.json", JSON.stringify(packageJson, null, 2));

    // 3. docs/PRD.md
    if (pmContent) {
      const prd = `# Product Requirements Document (PRD)
**Project**: ${pmContent.project ?? project.name}

## Business & Technical Goals
${(pmContent.goals ?? []).map((g: string) => `- ${g}`).join("\n")}

## Target Actors
${(pmContent.actors ?? []).map((a: any) => `- **${a.role}**: ${a.description}`).join("\n")}

## Feature Specifications & Priorities
${(pmContent.features ?? [])
  .map(
    (f: any) => `### [${f.id}] ${f.title} (${f.priority.toUpperCase()})
${f.description}
`
  )
  .join("\n")}

## Acceptance Criteria (Given/When/Then)
${(pmContent.acceptanceCriteria ?? [])
  .map(
    (ac: any) => `#### [${ac.featureId}] ${ac.scenario}
- **Given**: ${ac.given}
- **When**: ${ac.when}
- **Then**: ${ac.then}
`
  )
  .join("\n")}

## Operational Constraints
${(pmContent.constraints ?? []).map((c: string) => `- ${c}`).join("\n")}
`;
      await writeFile("docs/PRD.md", prd);
    }

    // 4. docs/ARCHITECTURE.md
    if (archContent) {
      const arch = `# Architecture Specification

## Topology & Pattern
**Pattern**: ${archContent.architecture?.pattern ?? "Modular Monolith"}

### Core Components
${(archContent.architecture?.components ?? [])
  .map((c: any) => `- **${c.name}** (${c.role}): Technologies: ${c.technologies?.join(", ")}`)
  .join("\n")}

## Database Strategy
- **Engine**: ${archContent.database?.engine ?? "PostgreSQL"}
- **Entities**: ${archContent.database?.entities?.join(", ") ?? "Core models"}
- **Strategy**: ${archContent.database?.strategy ?? "Prisma ORM with Migrations"}

## API Contracts
${(archContent.apis ?? [])
  .map(
    (api: any) => `### \`${api.method} ${api.endpoint}\`
- **Description**: ${api.description}
- **Response Schema**: \`${api.responseSchemaName}\`
`
  )
  .join("\n")}

## Architecture Decision Records (ADRs)
${(archContent.decisions ?? [])
  .map(
    (d: any) => `### ADR: ${d.title}
- **Decision**: ${d.decision}
- **Alternatives Considered**: ${d.alternatives?.join(", ")}
- **Tradeoffs**: ${d.tradeoffs}
`
  )
  .join("\n")}
`;
      await writeFile("docs/ARCHITECTURE.md", arch);
    }

    // 5. Prisma Schema (prisma/schema.prisma)
    if (dbContent) {
      const prismaFragment = dbContent.prismaSchemaFragment ?? `
model User {
  id        String   @id @default(uuid())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
}
`;
      const schemaPrisma = `// Prisma Schema generated by ForgeOS Database Agent
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

${prismaFragment}
`;
      await writeFile("prisma/schema.prisma", schemaPrisma);

      if (dbContent.migrationPlan && Array.isArray(dbContent.migrationPlan)) {
        await writeFile(
          "prisma/migrations/01_init.sql",
          `-- Initial migration plan generated by ForgeOS\n` + dbContent.migrationPlan.join(";\n") + ";"
        );
      }
    }

    // 6. Backend Fastify Server & Routes
    if (backendContent) {
      const routesCode = (backendContent.routes ?? [])
        .map((r: any) => {
          return `  // ${r.method} ${r.path}: ${r.handlerDescription}
  fastify.${r.method.toLowerCase()}("${r.path}", async (request, reply) => {
    return {
      status: "success",
      endpoint: "${r.path}",
      data: { message: "Handler for ${r.path} executed successfully" }
    };
  });`;
        })
        .join("\n\n");

      const serverTs = `import fastify from "fastify";
import cors from "@fastify/cors";

const app = fastify({ logger: true });

await app.register(cors, { origin: true });

app.get("/health", async () => ({ status: "ok", timestamp: new Date().toISOString() }));

${routesCode}

const start = async () => {
  try {
    const port = Number(process.env["PORT"] ?? 4000);
    await app.listen({ port, host: "0.0.0.0" });
    console.log(\`Server running on http://localhost:\${port}\`);
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }
};

start();
`;
      await writeFile("src/server.ts", serverTs);

      // Services
      if (backendContent.services && Array.isArray(backendContent.services)) {
        for (const service of backendContent.services) {
          const svcCode = `export class ${service.name} {
${(service.methods ?? []).map((m: string) => `  public async ${m}() {\n    return { success: true, method: "${m}" };\n  }`).join("\n\n")}
}
`;
          await writeFile(`src/services/${service.name.toLowerCase()}.service.ts`, svcCode);
        }
      }

      // Unit Tests
      if (backendContent.unitTests && Array.isArray(backendContent.unitTests)) {
        const testsCode = `import { describe, it, expect } from "vitest";

describe("Backend API Unit Tests", () => {
${backendContent.unitTests
  .map(
    (t: any) => `  it("${t.testName} - ${t.scenario.replace(/"/g, '\\"')}", async () => {
    expect(true).toBe(true);
  });`
  )
  .join("\n")}
});
`;
        await writeFile("tests/api.test.ts", testsCode);
      }
    }

    // 7. Frontend UI Specification & Components
    if (uiContent) {
      if (uiContent.components && Array.isArray(uiContent.components)) {
        for (const comp of uiContent.components) {
          const propsInterface = (comp.props ?? []).length > 0
            ? `interface ${comp.name}Props {\n${comp.props.map((p: string) => `  ${p.includes(":") ? p : `${p}?: any;`}`).join("\n")}\n}\n\n`
            : "";

          const compCode = `import React from "react";

${propsInterface}/**
 * ${comp.description}
 */
export const ${comp.name}: React.FC<${(comp.props ?? []).length > 0 ? `${comp.name}Props` : "{}"}> = (props) => {
  return (
    <div className="p-4 rounded-lg bg-slate-900 border border-slate-800 text-white">
      <h3 className="text-lg font-bold mb-2">${comp.name}</h3>
      <p className="text-sm text-slate-400 mb-4">${comp.description}</p>
      <div className="text-xs text-slate-500 font-mono">
        Props: {JSON.stringify(props)}
      </div>
    </div>
  );
};

export default ${comp.name};
`;
          await writeFile(`src/components/${comp.name}.tsx`, compCode);
        }
      }

      // Main Page
      const pageCode = `import React from "react";
${(uiContent.components ?? []).map((c: any) => `import { ${c.name} } from "./components/${c.name}";`).join("\n")}

export default function HomePage() {
  return (
    <main className="min-h-screen bg-slate-950 text-slate-100 p-8">
      <header className="mb-8">
        <h1 className="text-3xl font-extrabold tracking-tight">${project.name}</h1>
        <p className="text-slate-400 mt-2">${project.requirement}</p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
${(uiContent.components ?? []).map((c: any) => `        <${c.name} />`).join("\n")}
      </div>
    </main>
  );
}
`;
      await writeFile("src/app/page.tsx", pageCode);
    }

    return {
      exportDir: targetDir,
      files: createdFiles,
      totalFiles: createdFiles.length,
    };
  }
}
