-- Initial migration plan generated by ForgeOS
CREATE TABLE "CoreEntity" (id UUID PRIMARY KEY, title TEXT NOT NULL, status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);;
CREATE INDEX idx_core_entity_status ON "CoreEntity" (status);;
